//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiCareHMSReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeeNextOfKins = new HashSet<EmployeeNextOfKin>();
        }
    
        public System.Guid Id { get; set; }
        public string DesignationId { get; set; }
        public System.Guid DepartmentId { get; set; }
        public System.Guid HospitalId { get; set; }
        public string RegistrationCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string IdNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string NHIFNumber { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Specializations { get; set; }
        public string KRAPIN { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public int CountyId { get; set; }
        public string Town { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeNextOfKin> EmployeeNextOfKins { get; set; }
    }
}
