//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiCareHMSReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalVisit
    {
        public System.Guid Id { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid HospitalId { get; set; }
        public System.Guid ServiceId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Token { get; set; }
        public string CreatedBy { get; set; }
        public string VisitCode { get; set; }
        public string ReceptionRemarks { get; set; }
        public byte PaymentStatus { get; set; }
        public byte TriageStatus { get; set; }
        public byte DoctorStatus { get; set; }
        public byte LabRequestStatus { get; set; }
        public string TransactionNumber { get; set; }
        public bool isActive { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
