//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiCareHMSReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public System.Guid Id { get; set; }
        public string CompanyName { get; set; }
        public string PhoneNumber { get; set; }
        public string PostalAddress { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public int CountryId { get; set; }
        public string Town { get; set; }
        public string PhysicalAddress { get; set; }
        public string WebsiteURL { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
