//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiCareHMSReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabRequestDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid TestId { get; set; }
        public System.Guid VisitId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string RequestedBy { get; set; }
        public System.Guid RequestId { get; set; }
        public byte PaymentStatus { get; set; }
        public byte ResultStatus { get; set; }
    
        public virtual LabRequest LabRequest { get; set; }
    }
}
