//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiCareHMSReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabRequest()
        {
            this.LabRequestDetails = new HashSet<LabRequestDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid VisitId { get; set; }
        public string Note { get; set; }
        public string RequestedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte PaymentStatus { get; set; }
        public byte LabResultsStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabRequestDetail> LabRequestDetails { get; set; }
    }
}
