//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiCareHMSReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public System.Guid Id { get; set; }
        public string BarCode { get; set; }
        public string MedicineName { get; set; }
        public string Strength { get; set; }
        public string GenericName { get; set; }
        public System.Guid UnitId { get; set; }
        public System.Guid ShelfId { get; set; }
        public string Note { get; set; }
        public System.Guid CategoryId { get; set; }
        public System.Guid MedicineTypeId { get; set; }
        public System.Guid ManufacturerId { get; set; }
        public decimal ManufacturerPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal Vat { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
