//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiCareHMSReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid PatientId { get; set; }
        public byte Epilepsy { get; set; }
        public byte Hypertension { get; set; }
        public byte Respiratory { get; set; }
        public byte Cardiac { get; set; }
        public byte DiabetesMellitus { get; set; }
        public string CreatedBy { get; set; }
        public string OtherMedicalHistory { get; set; }
        public System.Guid HospitalVisitId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid TriageId { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
