//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiCareHMSReport.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkiCareHMSEntities : DbContext
    {
        public SkiCareHMSEntities()
            : base("name=SkiCareHMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AppointmentLimit> AppointmentLimits { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public virtual DbSet<BedCategory> BedCategories { get; set; }
        public virtual DbSet<Bed> Beds { get; set; }
        public virtual DbSet<CashPayment> CashPayments { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<EmployeeNextOfKin> EmployeeNextOfKins { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<HospitalService> HospitalServices { get; set; }
        public virtual DbSet<HospitalVisit> HospitalVisits { get; set; }
        public virtual DbSet<InsurancePatient> InsurancePatients { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<LabRequestDetail> LabRequestDetails { get; set; }
        public virtual DbSet<LabRequest> LabRequests { get; set; }
        public virtual DbSet<LabResult> LabResults { get; set; }
        public virtual DbSet<LabTest> LabTests { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<MedicalHistory> MedicalHistories { get; set; }
        public virtual DbSet<MedicineCategory> MedicineCategories { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<MedicineType> MedicineTypes { get; set; }
        public virtual DbSet<MpesaExpressRespon> MpesaExpressRespons { get; set; }
        public virtual DbSet<ObstetricHistory> ObstetricHistories { get; set; }
        public virtual DbSet<PatientImage> PatientImages { get; set; }
        public virtual DbSet<PatientNextOfKin> PatientNextOfKins { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PharmacyService> PharmacyServices { get; set; }
        public virtual DbSet<PrescriptionDetail> PrescriptionDetails { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<Shelf> Shelves { get; set; }
        public virtual DbSet<SocialHistory> SocialHistories { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<StockMovement> StockMovements { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<Triage> Triages { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
