//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiCareHMSReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Triage
    {
        public System.Guid Id { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid HospitalVisitId { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BMI { get; set; }
        public string Respiration { get; set; }
        public string Pulse { get; set; }
        public string FoodAllergy { get; set; }
        public string DrugAllergy { get; set; }
        public string CreatedBy { get; set; }
        public string Temprature { get; set; }
        public string Diastolic { get; set; }
        public string Notes { get; set; }
        public string SP02 { get; set; }
        public string Systolic { get; set; }
        public string FamilyHistory { get; set; }
        public string SurgicalHistory { get; set; }
        public string TransfusionHistory { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
